Repository HilkopterBob/PackageLock, pull requests merged in 2024-10, with the labels that each got.

#60 Logging
  .gitignore
  certs/generate-certs.go
  config/conf-init.go
  config/conf-init_test.go.ignore
  config/mockgen.go.ignore
  db/db.go
  go.mod
  go.sum
  handler/UserGroup.go
  handler/agentgroup.go
  handler/generalgroup.go
  handler/hostgroup.go
  logger/logger.go
  main.go
  server/router.go
Labels: enhancement, New Feature

#61 Fix naming
  config/conf-init.go
  main.go
Labels: chore

#62 API-Fields
  handler/agentgroup.go
  server/router.go
Labels: enhancement, API

#71 fix+feat: correct init chain + add setup.
  main.go
Labels: enhancement, New Feature

#72 Generate systemd unit file
  main.go
Labels: New Feature

#73 Partial GitHub Actions merge for release
  .github/workflows/golangci-lint.yml
  .github/workflows/release_tag.yml
  .github/workflows/test-build.yml
  .github/workflows/unit-tests.yml
Labels: good first issue, New Feature

#75 fix: run initServer before startServer, close #74
  main.go
Labels: bug

#80 fix: #69 by creating a certs folder in current dir
  certs/generate-certs.go
  main.go
Labels: bug

#82 Fix 81
  logger/logger.go
Labels: bug

#85 feat: add command to print out all routes
  main.go
Labels: enhancement, developer experience, New Feature

#88 Go-uber fx restructuring
  certs/generate-certs.go
  cmd/generate.go
  cmd/print_routes.go
  cmd/restart.go
  cmd/root.go
  cmd/setup.go
  cmd/start.go
  cmd/stop.go
  config/conf-init.go
  db/db.go
  go.mod
  go.sum
  handler/UserGroup.go
  handler/agentgroup.go
  handler/generalgroup.go
  handler/handler.go
  handler/hostgroup.go
  logger/logger.go
  main.go
  server/router.go
Labels: enhancement, developer experience

#93 feat: log rotation
  go.mod
  go.sum
  logger/logger.go
Labels: enhancement

#95 Fix #94
  cmd/root.go
Labels: bug

#96 feat: show appversion in 404 not found page
  server/router.go
  templates/404.html
Labels: enhancement

#101 Publish to wiki
  .github/workflows/publish-wiki.yml
  wiki/API-Docs.md
  wiki/API/agents/_Sidebar.md
  wiki/API/agents/get_agent_by_id.md
  wiki/API/agents/register_agent.md
  wiki/API/auth/_Sidebar.md
  wiki/API/auth/access-token.md
  wiki/API/auth/login.md
  wiki/API/general/_Sidebar.md
  wiki/API/general/get_agents.md
  wiki/API/general/get_hosts.md
  wiki/API/hosts/_Sidebar.md
  wiki/API/hosts/get_host_by_agentid.md
  wiki/API/hosts/register_host.md
  wiki/Home.md
  wiki/_Footer.md
  wiki/_Sidebar.md
Labels: developer experience

#106 Wiki
  LICENSE
  wiki/developer docs/Architecture-Overview.md
  wiki/developer docs/Contributing.md
  wiki/developer docs/Dev-Home.md
  wiki/developer docs/FAQ.md
  wiki/developer docs/Getting-Started.md
  wiki/developer docs/Style-Guide.md
  wiki/developer docs/_Sidebar.md
  wiki/developer docs/tracing.md
Labels: documentation, developer experience

#102 Tracing
  .github/workflows/build-docker-container.yml
  .github/workflows/unstable-build-docker-container.yml
  cmd/generate.go
  cmd/start.go
  config/conf-init.go
  db/db.go
  go.mod
  go.sum
  main.go
  server/router.go
  tools/Dockerfile
  tools/Dockerfile-tracing
  tracing/tracing.go
Labels: enhancement, developer experience, New Feature

#108 docs: add TRACING_JAEGER_URL description && directions
  wiki/developer docs/tracing.md
Labels: documentation

#116 Change: Wiki-Optimization regarding: #109
  wiki/developer docs/Dev-Home.md
  wiki/developer docs/_Sidebar.md
Labels: bug, documentation, enhancement

#118 FIX: Fixed broken Links
  wiki/_Sidebar.md
  wiki/developer docs/Dev-Home.md
Labels: bug, documentation

#117 chore: bump dependency version(s)
  go.mod
  go.sum
Labels: chore

#121 GitHub actions - Add nigtly builds
  .github/workflows/nightly_release.yml
  README.md
Labels: ci/cd

#122 Change: add nightly_release Workflow to default Branch
  .github/workflows/nightly_release.yml
Labels: bug, ci/cd

#123 Change: Attempting to fix Nightly-Build Workflow
  .github/workflows/nightly_release.yml
Labels: bug, ci/cd

#128 fix: sonar issue report
  templates/404.html
Labels: Code Scanner

#113 feat: monitoring
  config/conf-init.go
  go.mod
  go.sum
  server/router.go
Labels: enhancement, stopped
